config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { 
      sessions:      'users/sessions',
      registrations: 'users/registrations',
    }   

  authenticate :user do
    namespace :admin do
      resources :users
    end

    post  'houses_filter',             to: 'houses_filter#index',        as: 'houses_filter'
    get   'house_annual_contribs/:id', to: 'house_contribs#annual',      as: 'house_annual_contribs'
    get   'house_detail_contribs/:id', to: 'house_contribs#detail',      as: 'house_detail_contribs'
    get   'house_occupants/:id',       to: 'house_occupants#occupants',  as: 'house_occupants'
    get   'house_owners/:id',          to: 'house_owners#owners',        as: 'house_owners'

    get   'contributions/new_for_house/:house_id', to: 'contributions#new_for_house',  as: 'new_contrib_for_house'
    get   'contributions/:id/edit_for_house',      to: 'contributions#edit_for_house', as: 'edit_contrib_for_house'

    get   'person_email_addrs/:id',    to: 'person_email_addrs#email_addrs', as: 'person_email_addrs'
    get   'person_phone_numbers/:id',  to: 'person_phone_numbers#ph_nums',   as: 'person_phone_numbers'
    get   'person_addresses/:id',      to: 'person_addresses#addresses',     as: 'person_addresses'
 
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'

    get   '/non_occupants',         to: 'non_occupants#index',     as: 'list_non_occupants'
    patch '/non_occupant/:id',      to: 'non_occupants#update',    as: 'update_non_occupant'

    get   'roster',                 to: 'roster#roster',           as: 'roster'

    resources :people do
      collection do
        get 'houses'
      end
    end

    resources :streets

    resources :addresses, :phones, :emails, 
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/non_occupants_controller.rb
# frozen_string_literal: true

class NonOccupantsController < ApplicationController
  def index
    @q = non_occup_query
    @pagy, @non_occupants = pagy(@q.result)
    @house_id = params.dig(:q,:house_id) || params.dig(:house_id)
  end

  def update
    redirect_to houses_path and return unless house_id
    non_occupant = Person.find(params[:id])
    if non_occupant.update(house_id: house_id)
      redirect_to house_path(id: house_id), notice: 'An occupant was added.'
    else
      render :index
    end
  end

  private

  def non_occup_query
    Person
      .where(house_id: nil)
      .order(last: :asc, first: :asc, middle: :asc)
      .ransack(params[:q])
  end

  def house_id
    @house_id ||= existing_house_id
  end

  def existing_house_id
    House.find(house_id_as_UUID_from_params).id
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def house_id_as_UUID_from_params
    params[:house_id].match(SharedRegexp::UUID_FORMAT)[0]
  end
end

app/views/non_occupants/_head.html.erb
<tr>
  <th scope="col" class="th-pad th-base"><%= sort_link(@q,:sortable_name,'Name', class: 'font-sans') %></th>
  <th scope="col" class="th-pad th-base hidden lg:table-cell"><%= sort_link(@q,:nickname, class: 'font-sans') %></th>
  <th scope="col" class="th-pad th-base hidden lg:table-cell">Role</th>
  <th scope="col" class="th-pad th-base hidden lg:table-cell">Status</th>
  <th colspan="1"></th>
</tr>

app/views/non_occupants/_row.html.erb
<% present(item) do |item| %>
  <tr class='<%= background %>' >

    <td class='td-pad td-emphasized'>
      <%= link_to item.sortable_name, person_path(item), class: "td-emphasized link-hover" %>
    </td>

    <td class='td-pad td-base hidden lg:table-cell'><%= item.nickname %></td>
    <td class='td-pad td-base hidden lg:table-cell'><%= item.role %></td>
    <td class='td-pad td-base hidden lg:table-cell'><%= item.status %></td>

    <td class='td-pad td-emphasized'>
      <%= link_to 'Add to a House', edit_person_path(item), class: "font-sans font-medium link-hover" %>
    </td>

  </tr>
<% end %>

app/views/non_occupants/_search_form.html.erb
<%= search_form_for @q, url: list_non_occupants_url do |f| %>
  <%= f.hidden_field :house_id, value: @house_id %>

  <div class="row">
    <div class="col-sm-5">
      <%= f.label :last_cont %>
      <%= f.search_field :last_cont %>
    </div>

    <div class="col-sm-2">
      <%= f.submit %>
    </div>

    <div class="col">
      <%= link_to "Clear", list_non_occupants_path(house_id: @house_id) %>
    </div>
  </div>

<% end %>

app/views/non_occupants/index.html.erb
<div class='flex flex-col sm:flex-row items-center justify-center'>
  <div class='mb-5 mx-2'>
    <div class="flex flex-row justify-between">
      <h1 class="font-sans font-bold text-2xl">Non-Occupants</h1>
    </div>

    <%= render "shared/table", 
            head: 'head', 
            item_row:  'row', 
            collection: @non_occupants 
    %>

    <br>
    <%== pagy_nav(@pagy) %>

    <hr class="mt-1 border-1 border-gray-700" />
    <br>

    <%= link_to 'New Person', new_person_path, class: "text-lg font-sans font-medium link-hover" %> 
  </div>
</div>

app/views/non_occupants/new.html.erb
<div class="grid grid-cols-1 sm:grid-cols-6 mt-2 gap-x-6 gap-y-2">
  <div class="col-start-1 col-end-6 sm:col-start-2">

    <h1 class="text-2xl font-extrabold">New Non Occupant</h1>

    <%= render 'shared/form', mdl: @person %>

    <hr class="border-1 border-gray-700 cursor-pointer hover:border-red-500" />

    <%= link_to 'Non Occupant List', list_non_occupants_path, class: "text-lg text-bold" %>

  </div>
</div>