config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { 
      sessions:      'users/sessions',
      registrations: 'users/registrations',
    }   

  authenticate :user do
    namespace :admin do
      resources :users
    end

    post  'houses_filter',             to: 'houses_filter#index',        as: 'houses_filter'
    get   'house_annual_contribs/:id', to: 'house_contribs#annual',      as: 'house_annual_contribs'
    get   'house_detail_contribs/:id', to: 'house_contribs#detail',      as: 'house_detail_contribs'
    get   'house_occupants/:id',       to: 'house_occupants#occupants',  as: 'house_occupants'
    get   'house_owners/:id',          to: 'house_owners#owners',        as: 'house_owners'

    get   'contributions/new_for_house/:house_id', to: 'contributions#new_for_house',  as: 'new_contrib_for_house'
    get   'contributions/:id/edit_for_house',      to: 'contributions#edit_for_house', as: 'edit_contrib_for_house'

    get   'person_email_addrs/:id',    to: 'person_email_addrs#email_addrs', as: 'person_email_addrs'
    get   'person_phone_numbers/:id',  to: 'person_phone_numbers#ph_nums',   as: 'person_phone_numbers'
    get   'person_addresses/:id',      to: 'person_addresses#addresses',     as: 'person_addresses'
 
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'

    get   '/non_occupants',         to: 'non_occupants#index',     as: 'list_non_occupants'
    patch '/non_occupant/:id',      to: 'non_occupants#update',    as: 'update_non_occupant'

    get   'roster',                 to: 'roster#roster',           as: 'roster'

    resources :people do
      collection do
        get 'houses'
      end
    end

    resources :streets

    resources :addresses, :phones, :emails, 
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[show detail edit update destroy contribs]

  # GET /houses
  def index
    @q = House.includes(:lots).ransack(params[:q])
    @q.sorts = ['street asc', 'number asc'] if @q.sorts.empty?
    @pagy, @houses = pagy(@q.result)
  end

  # GET /houses/1
  def show; end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit; end

  # POST /houses
  def create
    @house = House.new(house_params)
    if @house.save
      redirect_to @house, notice: 'House was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /houses/1
  def update
    if @house.update(house_params)
      redirect_to @house, notice: 'House was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /houses/1
  def destroy
    @house.destroy
    redirect_to houses_url, status: :see_other, notice: 'House was successfully destroyed.'
  end

  private

  def set_house
    @house = House.find(params[:id])
  end

  def house_params
    params.require(:house).permit(:number, :street, :lat, :lng, :image_link,
                                  :flag, :rental, :listed, :status, :note, lot_ids: [])
  end
end

app/helpers/houses_helper.rb
# frozen_string_literal: true

module HousesHelper
end

app/views/houses/_filter.html.erb
<div class="flex items-center justify-center">
  <div class="w-3/4 min-w-max">
    <%= render "houses/filter/search_form" %>
  </div>
</div>

app/views/houses/_head.html.erb
<tr>
	<th scope="col" class="th-pad">
	  <%= sort_link(@q,:house_address, [:street, :number], 'Address', class: 'font-sans') %>
	</th>

	<th scope="col" class="th-pad hidden md:table-cell">
	  <%= sort_link(@q,:flag, class: 'font-sans') %>
	</th>

	<th scope="col" class="th-pad hidden lg:table-cell">
	  <%= sort_link(@q,:rental, class: 'font-sans') %>
	</th>

	<th scope="col" class="th-pad hidden lg:table-cell">
	  <%= sort_link(@q,:listed, class: 'font-sans') %>
	</th>

	<th scope="col" class="th-pad hidden lg:table-cell">
	  <%= sort_link(@q,:status, class: 'font-sans') %>
	</th>

	<th scope="col" class="th-pad font-sans hidden xl:table-cell">Linked Lots</th>
	<th scope="col" class="th-pad font-sans hidden md:table-cell">Notes</th>
</tr>

app/views/houses/_row.html.erb
<% present(item) do |item| %>
  <tr class='<%= background %>' >
    <td class='td-pad'>
      <%= link_to item.house_address, house_path(item), class: "td-emphasized link-hover" %>
    </td>
    <td class='td-pad td-base hidden md:table-cell'><%= item.gets_flag %></td>
    <td class='td-pad td-base hidden lg:table-cell'><%= item.is_rented %></td>
    <td class='td-pad td-base hidden lg:table-cell'><%= item.is_listed %></td>
    <td class='td-pad td-base hidden lg:table-cell'><%= item.status %></td>
    <td class='td-pad td-base hidden xl:table-cell'><%= item.linked_lot_addresses %></td>
    <td class='td-pad td-base hidden md:table-cell'><%= item.note_hint %></td>

  </tr>
<% end %>

app/views/houses/edit.html.erb
<div class="max-w-4xl mb-5 font-semibold">
    <h1 class="text-2xl font-sans font-extrabold">Edit House</h1>
    <%= render 'shared/form', mdl: @house, editing: true %>
</div>

app/views/houses/index.html.erb
<div class='flex flex-col sm:flex-row items-center justify-center'>
  <div class="mb-5 mx-2">
    <div class="flex flex-row justify-between">

      <h1 class="font-sans font-bold text-2xl">Houses</h1>

      <div class="group inline-block focus:block relative">
        <button class="p-4 font-sans font-bold text-1xl text-black bg-gray-100 rounded-md border-none">Filter</button>
        <div class="hidden group-hover:block absolute min-w-full right-0 z-10 rounded-xl">
          <%= render "filter" %>
        </div>
      </div>
      
    </div>

    <%= render "shared/table", 
            head:      'head',
            item_row:  'row', 
            collection: @houses 
    %>

    <br>
    <%== pagy_nav(@pagy) %>

    <hr class="mt-1 border-1 border-gray-700" />
    <br>

    <%= link_to 'New House', new_house_path, class: "text-lg font-sans font-medium link-hover" %>
  </div>
</div>

app/views/houses/new.html.erb
<div class="max-w-4xl mb-5">
    <h1 class="text-2xl font-sans font-extrabold">New House</h1>
    <%= render 'shared/form', mdl: @house, editing: false %>
</div>

app/views/houses/show.html.erb
<% present(@house) do |house| %>
<div class="flex flex-col items-center justify-center">

  <div class='grid grid-rows-auto'>
    <div class='row-start-1 max-h-fit'>

      <div class='grid auto-rows-min grid-rows-auto'>
        <header class='row-start-1'>
          <h1 class="mb-2 text-2xl font-sans font-bold"><%= house.house_address %></h1>
        </header>

        <div class='row-start-2 h-fit mb-3'>
            <%= render "shared/show/attrib",
                  attributes: [
                    {attribute: house.status, label: 'Status'},
                    {attribute: house.gets_flag, label: 'Flag'},
                    {attribute: house.is_rented, label: 'Rental'},
                    {attribute: house.is_listed, label: 'Listed'}
                  ]
            %>
        </div>

        <div class='row-start-3 -mb-1 h-fit'>
          <h2 class="pl-2 text-base font-sans font-bold text-left">Contributions:</h2>
        </div>

        <div class='row-start-4 h-fit mb-3'>
            <%= render "shared/show/attrib",
                  attributes: [
                      { attribute: house.this_yr_contrib,
                        label: house.this_year },
                      { attribute: house.last_yr_contrib,
                        label: house.last_year}
                  ]
            %>
        </div>

        <div class='row-start-5 h-fit mb-3'>
            <%= render "shared/show/attrib",
                  attributes: [
                    {attribute: house.lat, label: 'Latitude'},
                    {attribute: house.lng, label: 'Longitude'},
                    {attribute: house.image_link, label: 'Image Lnk'}
                  ]
            %>
        </div>

        <div class='row-start-6 h-fit mb-3'>
            <%= render "shared/show/note", attribute: house.note, label: 'Note' %>
        </div>
      </div>
    </div>

    <div class='row-start-2 h-fit my-4'>
      <%= link_to 'Contribution Detail', house_annual_contribs_path(house), class: "mx-1 py-2 px-4 rounded bg-gray-500 hover:bg-gray-700 text-white font-sans font-bold" %>

      <%= link_to 'Occupants', house_occupants_path(house), class: "mx-1 py-2 px-4 rounded bg-gray-500 hover:bg-gray-700 text-white font-sans font-bold" %>

      <%= link_to 'Owners', house_owners_path(house), class: "mx-1 py-2 px-4 rounded bg-gray-500 hover:bg-gray-700 text-white font-sans font-bold" %>
    </div>

    <div class='row-start-4 h-fit my-3'>
      <%= render "shared/show/edit_btn", path: edit_house_path(house) %>
      <%= render "shared/show/back_btn", path: houses_path %>
      <%= render "shared/show/delete_btn", path: house_path(house) %>
    </div>
  </div>

</div>
<% end %>