config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { 
      sessions:      'users/sessions',
      registrations: 'users/registrations',
    }   

  authenticate :user do
    namespace :admin do
      resources :users
    end

    post  'houses_filter',             to: 'houses_filter#index',        as: 'houses_filter'
    get   'house_annual_contribs/:id', to: 'house_contribs#annual',      as: 'house_annual_contribs'
    get   'house_detail_contribs/:id', to: 'house_contribs#detail',      as: 'house_detail_contribs'
    get   'house_occupants/:id',       to: 'house_occupants#occupants',  as: 'house_occupants'
    get   'house_owners/:id',          to: 'house_owners#owners',        as: 'house_owners'

    get   'contributions/new_for_house/:house_id', to: 'contributions#new_for_house',  as: 'new_contrib_for_house'
    get   'contributions/:id/edit_for_house',      to: 'contributions#edit_for_house', as: 'edit_contrib_for_house'

    get   'person_email_addrs/:id',    to: 'person_email_addrs#email_addrs', as: 'person_email_addrs'
    get   'person_phone_numbers/:id',  to: 'person_phone_numbers#ph_nums',   as: 'person_phone_numbers'
    get   'person_addresses/:id',      to: 'person_addresses#addresses',     as: 'person_addresses'
 
    get   '/people/occupant/:house_id', to: 'people#new_occupant', as: 'new_occupant'

    get   '/non_occupants',         to: 'non_occupants#index',     as: 'list_non_occupants'
    patch '/non_occupant/:id',      to: 'non_occupants#update',    as: 'update_non_occupant'

    get   'roster',                 to: 'roster#roster',           as: 'roster'

    resources :people do
      collection do
        get 'houses'
      end
    end

    resources :streets

    resources :addresses, :phones, :emails, 
              :person_phones, :person_addresses,
              :houses, :ownerships, :contributions,
              :positions
    root 'welcome#home', as: :root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/contribution.rb
# frozen_string_literal: true

class Contribution < ApplicationRecord
  belongs_to :house

  validates :house_id,  presence: true
  validates :date_paid, presence: true

  monetize :amount_cents, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/contributions_controller.rb
# frozen_string_literal: true

class ContributionsController < ApplicationController
  before_action :set_contribution, only: %i[show edit edit_for_house update destroy]

  # GET /contributions
  def index
    @pagy, @contributions = pagy(Contribution.all)
  end

  # GET /contributions/1
  def show; end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/new_for_house/:house_id
  def new_for_house
    @contribution = Contribution.new
    @contribution.house_id = params[:house_id]
  end

  # GET /contributions/1/edit
  def edit; end

  # GET /contributions/:id/edit_for_house
  def edit_for_house; end

  # POST /contributions
  def create
    @contribution = Contribution.new(contribution_params)
    if @contribution.save
      redirect_to @contribution, notice: 'Contribution was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contributions/1
  def update
    if @contribution.update(contribution_params)
      redirect_to @contribution, notice: 'Contribution was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contributions/1
  def destroy
    @contribution.destroy
    redirect_to contributions_url, status: :see_other, notice: 'Contribution was successfully destroyed.'
  end

  private

  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(:house_id, :date_paid, :amount)
  end
end

app/helpers/contributions_helper.rb
# frozen_string_literal: true

module ContributionsHelper
end

app/views/contributions/_head.html.erb
<tr>
  <th scope="col" class="th-pad th-base">House</th>
  <th scope="col" class="th-pad th-base">Date Paid</th>
  <th scope="col" style="text-align:right"  class="th-pad th-base ">Amount</th>
</tr>

app/views/contributions/_row.html.erb
<% present(item) do |item| %>
  <tr class='<%= background %>' >

    <td class='td-pad'>
      <%= link_to item.house_address, contribution_path(item), class: "td-emphasized link-hover" %>
    </td>

    <td class='td-pad td-base'><%= item.date_paid %></td>
    <td style="text-align:right" class='td-pad td-base'><%= humanized_money_with_symbol(item.amount) %></td>

  </tr>
<% end %>

app/views/contributions/edit.html.erb
<div class="max-w-4xl mb-5">
  <h1 class="text-2xl font-sans font-extrabold">Edit Contribution</h1>
  <%= render 'shared/form', mdl: @contribution, editing: true %>
</div>

app/views/contributions/edit_for_house.html.erb
<div class="max-w-4xl mb-5">
  <h1 class="text-2xl font-sans font-extrabold">Edit Contribution</h1>
  <%= render 'shared/form', mdl: @contribution, editing: true %>
</div>

app/views/contributions/index.html.erb
<div class='flex flex-col sm:flex-row items-center justify-center'>
  <div class='mb-5 mx-2'>
    <div class="flex flex-row justify-between">
      <h1 class="font-sans font-bold text-2xl">Contributions</h1>
    </div>

    <%= render "shared/table", 
            head: 'head', 
            item_row:  'row', 
            collection: @contributions 
    %>

    <br>
    <%== pagy_nav(@pagy) %>

    <hr class="mt-1 border-1 border-gray-700" />
    <br>

    <%= link_to 'New Contribution', new_contribution_path, class: "text-lg font-sans font-medium link-hover" %> 
  </div>
</div>

app/views/contributions/new.html.erb
<div class="max-w-4xl mb-5">
  <h1 class="text-2xl font-sans font-extrabold">New Contribution</h1>
  <%= render 'shared/form', mdl: @contribution, editing: false %>
</div>

app/views/contributions/new_for_house.html.erb
<div class="max-w-4xl mb-5">
  <h1 class="text-2xl font-sans font-extrabold">New Contribution</h1>
  <%= render 'shared/form', mdl: @contribution, editing: true %>
</div>

app/views/contributions/show.html.erb
<% present(@contribution) do |contribution| %>
<div class="flex flex-col items-center justify-center">

  <div class='grid grid-rows-auto'>
    <div class='row-start-1 max-h-fit'>

      <div class='grid auto-rows-min grid-rows-auto'>
        <header class='row-start-1'>
          <h1 class="mb-2 text-2xl font-sans font-bold">Contribution Detail</h1>
        </header>

        <div class='row-start-2 h-fit mb-3'>
          <%= render "shared/show/attrib_wide",
            attribute: contribution.house_address, label: 'House'
          %>
        </div>

        <div class='row-start-3 h-fit mb-3'>
          <%= render "shared/show/attrib",
            attributes: [
              {attribute: contribution.date_paid, label: 'Date Paid'},
              {attribute: contribution.amount, label: 'Amount'},
            ]
          %>
        </div>
      </div>
    </div>

    <div class='row-start-2 h-fit my-3'>
      <%= render "shared/show/edit_btn", path: edit_contribution_path(contribution) %>
      <%= render "shared/show/back_btn", path: contributions_path %>
      <%= render "shared/show/delete_btn", path: contribution_path(contribution) %>
      <%= render "shared/show/house_btn", path: house_path(contribution.house_id) %>
    </div>
  </div>

</div>
<% end %>